import turtle
emot = turtle.Turtle()

emot.penup()
emot.goto(0, -10)
emot.pendown()
emot.color('yellow')
emot.begin_fill()
emot.circle(100)
emot.end_fill()

emot.color('black')
emot.pensize(5)
emot.penup()
emot.goto(0, -10)
emot.pendown()
emot.circle(100)

emot.pensize(1)
emot.penup()
emot.goto(-40,100)
emot.pendown()
emot.begin_fill()
emot.circle(20)
emot.end_fill()

emot.penup()
emot.goto(40,100)
emot.pendown()
emot.begin_fill()
emot.circle(20)
emot.end_fill()

emot.pensize(5)
emot.color('black')
emot.penup()
emot.goto(0,0)
emot.begin_fill()
emot.pendown()
emot.circle(60,90)
emot.end_fill()

emot.begin_fill()
emot.penup()
emot.setheading(180)
emot.goto(0,0)
emot.pendown()
emot.circle(-60,90)
emot.end_fill()

emot.begin_fill()
emot.penup()
emot.goto(-60, 60)
emot.pendown()
emot.goto(60, 60)
emot.end_fill()

emot.pensize(0)
emot.penup()
emot.goto(100,300)
emot.pendown()
emot.goto(100,300)

turtle.done()